version: "3.9"
services:
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  app:
    image: "node:alpine"
    command: "npm i -g npm && npm run build && npm run start && ls ./dist"
    working_dir: "/app"
    volumes:
      - "./:/app"
    ports:
      - 3000
