version: "3.9"
services:
  dynamo:
    image: amazon/dynamodb-local
    hostname: dynamodb
    restart: always
    ports:
      - 8000:8000
      - 8001:8001
    command: "-jar DynamoDBLocal.jar -sharedDb"
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5432:5432
  # redis:
  #   image: "redis:latest"
  app:
    image: "node:alpine"
    command: "npm i -g npm && npm run build && npm run start && ls ./dist"
    working_dir: "/app"
    volumes:
      - "./:/app"
    ports:
      - 3000
